### ISSUE TITLE
IGCV3 performance data

### ISSUE THREAD

**Issue by cvtower** [osmr/imgclsmob#11]
Hi @osmr ,

Nice work!
How did you get the IGCV3 performance on imagenet, did you train the model by yourself or cite acc data from original repo? Since i found the acc of IGCV3(IGCV3 x1.0) differs from the original repo(72.2).

**Comment by osmr** [comment]
Hi.
All quality indicators in the README tables are revalued by me. If the mark `Training` is not indicated in the `Remarks` field, then the model is converted. Usually the conversion requires a little additional training of the model, since I use standard normalization for all models, but the original models often use custom preprocessing.

**Comment by cvtower** [comment]
@osmr ,

Okey.
Since the original mxnet repo on github did not contain retrain module and this module is not open-source but important to reproduce performance, i will directly cite the acc value on the paper.

Thanks for your answer.
