### ISSUE TITLE
training/eval examples

### ISSUE THREAD

**Issue by kirk86** [osmr/imgclsmob#29]
Hi, thanks for the great repo.
I was wondering if you could provide some examples of train/eval scripts in order to train models that are currently missing from the repo, with sensible default params, so that we can contribute back any trained models currently missing? Maybe adding those train/eval script examples in the wiki would be valuable?

**Comment by osmr** [comment]
Good idea! I will definitely do it. But since this is a fairly large document, it will take me a certain amount of time. In the meantime, I can clarify certain points right here.

Training, testing, and conversion scripts are at the root of the repository. For historical reasons, I train models on MXNet, and then I convert them to other frameworks. Therefore, the MXNet training script is the most verified.

For choosing hyperparameters I almost entirely guided by the recommendations of the paper "Tong He et al. Bag of Tricks for Image Classification with Convolutional Neural Networks. 2018."

When you want to train a network, find a similar one from those already trained and analyze the training log (a link to this file is in the last column of the summary table). For example, `SE-ResNet-50b` model. The log-file is `seresnet50b-0533-0d8f0d23.params.log`. It consists of a log of the execution of two scripts:  `train_gl.py` and `eval_gl.py`. Change the name of the model and the name of the working folder of the model in the corresponding commands.

For training you need to choose the correct batch-size so that the model fits in the memory of the GPU (`batch-size` parameter). In addition, you need to adjust the value of the `batch-size-scale` parameter so that the product of the batch-size by this parameter gives approximately the number of classes, i.e. 1000 for ImageNet-1K.
